### ISSUE TITLE
Toggling for Alarm/Button Sounds

### ISSUE THREAD

**Issue by Juhmer-Tena** [kat066/biglunchbox-pomodoro#10]
- Description: Users can enable or disable the alarm and click sounds separately.
- User/Designer Goal: Users can toggle the alarm and click sounds separately if they find either one too distracting.
- Desired Outcome: Users can use a styled checkbox to toggle the alarm or click sound.
- Workflow:
  1. User opens settings pop-up
  2. User toggles on or off the respective sound
  3. Sound plays if it was just enabled to preview the change
  4. Localstorage settings gets on confirmation
- Alternative Workflow:
  iv. Sound toggles get reverted back on cancellation or early closure of the settings panel

**Comment by AxiosDeminence** [comment]
- Description: Users can enable or disable the alarm and click sounds separately.
- User/Designer Goal: Users can toggle the alarm and click sounds separately if they find either one too distracting.
- Desired Outcome: Users can use a styled checkbox to toggle the alarm or click sound.
- Workflow:
  1. User opens settings pop-up
  2. User toggles on or off the respective sound
  3. Sound plays if it was just enabled to preview the change
  4. Localstorage settings gets on confirmation
- Alternative Workflow:
  4. Sound toggles get reverted back on cancellation or early closure of the settings panel

**Comment by Juhmer-Tena** [comment]
Added in #13
