### ISSUE TITLE
Fix Settings Popup Responsiveness/Positioning

### ISSUE THREAD

**Issue by broiyn** [kat066/biglunchbox-pomodoro#23]
Need help with this.
When I add more settings in the popup, it runs out of room and the audio slider at the bottom doesn't show up anymore. I couldn't make it scrollable either.

**Comment by broiyn** [comment]
Need help with this.
When I add more settings in the popup, it runs out of room and the audio slider at the bottom doesn't show up anymore. I couldn't make it scrollable either.

**Comment by Burniee** [comment]
I know it's a bit late, but I'm also working on it, I'm trying to increase the size of the setting popup window, so the timer reset warning looks a bit cleaner.

**Comment by kat066** [comment]
Done and merged
