### ISSUE TITLE
Timer Reset Warning

### ISSUE THREAD

**Issue by Juhmer-Tena** [kat066/biglunchbox-pomodoro#9]
# Design Use Case

- Description: When the user goes into the settings, there is an indicator/warning for users that the timer will be stopped if they edit the session length settings if the timer is ongoing.
- User/Designer Goal: Users do not accidentally reset the timer or do not get confused when the timer resets after editing the session length settings.
- Desired Outcome: Users get an explicit indicator (ie. text) that the timer will reset when the session length settings get changed.
- Workflow: 
  1. User opens settings pop-up
  2. Users sees warning and knows any consequences of editing the timer settings
  3. User changes settings and confirms.
  4. Localstorage information gets updated and timer is reset to new values.
- Alternative Workflows
  iii. User cancels changing settings or closes the settings panel without confirming.
  iv. Localstorage information is not updated and timer settings are unchanged when re-opening the settings panel.

## Relevant ADRs
- [User Warnings for Timer Settings](https://github.com/kat066/biglunchbox-pomodoro/blob/408e6eeac4ee9a8004cab96271d0e9ee58e77c23/specs/adrs/042922-UserWarningTimerSettingsEdit.md)

**Comment by AxiosDeminence** [comment]
- Description: When the user goes into the settings, there is an indicator/warning for users that the timer will be stopped if they edit the session length settings if the timer is ongoing.
- User/Designer Goal: Users do not accidentally reset the timer or do not get confused when the timer resets after editing the session length settings.
- Desired Outcome: Users get an explicit indicator (ie. text) that the timer will reset when the session length settings get changed.
- Workflow: 
  - User opens settings pop-up
  - Users sees warning and knows any consequences of editing the timer settings
